title: Wilbert Peniche
#logo: /assets/img/headshot_circle.png
About Me: Data enthusiast with a knack for numbers and a background in economics and computer system engineering. Passionate about merging the worlds of finance and AI. Eager to harness the power of data to drive financial strategies, optimize investments, and decode economic trends.
Location: Monterrey, Nuevo Leon, Mexico

---

Contact:
[LinkedIn](https://www.linkedin.com/in/wilbert-peniche-19952b16a/)
Email: wilbertpeniche.wp@gmail.com
Mobile: +528661724465

show_downloads: true
theme: jekyll-theme-minimal
